-- Create a table with Oracle-specific data types
CREATE TABLE EMPLOYEES (
    EMP_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100) UNIQUE,
    HIRE_DATE DATE DEFAULT SYSDATE,
    SALARY NUMBER(10,2),
    DEPARTMENT_ID NUMBER(5) NOT NULL
);

-- Create a sequence to auto-generate EMP_ID
CREATE SEQUENCE EMP_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Trigger to auto-populate EMP_ID using sequence
CREATE OR REPLACE TRIGGER EMP_ID_TRIGGER
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF :NEW.EMP_ID IS NULL THEN
        SELECT EMP_SEQ.NEXTVAL INTO :NEW.EMP_ID FROM DUAL;
    END IF;
END;
/

-- Create an index on LAST_NAME column
CREATE INDEX IDX_EMP_LAST_NAME ON EMPLOYEES(LAST_NAME);

-- Create a procedure to give salary raise
CREATE OR REPLACE PROCEDURE GIVE_RAISE (
    p_emp_id IN NUMBER,
    p_percent IN NUMBER
) AS
BEGIN
    UPDATE EMPLOYEES
    SET SALARY = SALARY + (SALARY * p_percent / 100)
    WHERE EMP_ID = p_emp_id;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/