// Tie class generated by rmic, do not edit.
// Contents subject to change without notice.

package com;

import com.hp.sterling.jaxws.webservices.XBeanWSEnv;
import com.hp.sterling.jaxws.webservices.documentation.hpgetrmanumber.hpgetrmanumberservice.input.OrderXSDType;
import com.hp.sterling.jaxws.webservices.documentation.hpgetrmanumber.hpgetrmanumberservice.output.RMAXSDType;
import com.hp.sterling.jaxws.webservices.documentation.sendreturnorderdetails.hpsendreturnorderdetails.output.OrderListXSDType;
import com.hp.sterling.jaxws.webservices.documentation.updatenarvarreturnorder.updatenarvarreturnorder.output.ExtnFedExTransactionXSDType;
import com.sterlingcommerce.documentation.yfs.createenvironment.input.YFSEnvironmentXSDType;
import java.io.Serializable;
import java.lang.Object;
import java.lang.String;
import java.lang.Throwable;
import java.rmi.Remote;
import javax.ejb.EJBHome;
import javax.ejb.EJBObject;
import javax.ejb.Handle;
import javax.ejb.RemoveException;
import javax.rmi.CORBA.Tie;
import javax.rmi.CORBA.Util;
import org.omg.CORBA.BAD_OPERATION;
import org.omg.CORBA.ORB;
import org.omg.CORBA.SystemException;
import org.omg.CORBA.portable.Delegate;
import org.omg.CORBA.portable.InputStream;
import org.omg.CORBA.portable.OutputStream;
import org.omg.CORBA.portable.ResponseHandler;
import org.omg.CORBA.portable.UnknownException;

public class _EJSRemoteStatelessHPServicesBeansServiceSessionFac_c888ddcb_Tie extends org.omg.CORBA_2_3.portable.ObjectImpl implements Tie {
    
    private EJSRemoteStatelessHPServicesBeansServiceSessionFac_c888ddcb target = null;
    private ORB orb = null;
    
    private static final String[] _type_ids = {
        "RMI:com.HPServicesBeansServiceSessionFacade:0000000000000000", 
        "RMI:javax.ejb.EJBObject:0000000000000000", 
        "RMI:com.ibm.websphere.csi.CSIServant:0000000000000000", 
        "RMI:com.ibm.websphere.csi.TransactionalObject:0000000000000000"
    };
    
    public void setTarget(Remote target) {
        this.target = (EJSRemoteStatelessHPServicesBeansServiceSessionFac_c888ddcb) target;
    }
    
    public Remote getTarget() {
        return target;
    }
    
    public org.omg.CORBA.Object thisObject() {
        return this;
    }
    
    public void deactivate() {
        if (orb != null) {
            orb.disconnect(this);
            _set_delegate(null);
        }
    }
    
    public ORB orb() {
        return _orb();
    }
    
    public void orb(ORB orb) {
        orb.connect(this);
    }
    
    public void _set_delegate(Delegate del) {
        super._set_delegate(del);
        if (del != null)
            orb = _orb();
        else
            orb = null;
    }
    
    public String[] _ids() { 
        return (String [] )  _type_ids.clone();
    }
    
    public OutputStream _invoke(String method, InputStream _in, ResponseHandler reply) throws SystemException {
        try {
            org.omg.CORBA_2_3.portable.InputStream in = 
                (org.omg.CORBA_2_3.portable.InputStream) _in;
            switch (method.length()) {
                case 6: 
                    if (method.equals("remove")) {
                        return remove(in, reply);
                    }
                case 11: 
                    if (method.equals("_get_handle")) {
                        return _get_handle(in, reply);
                    } else if (method.equals("isIdentical")) {
                        return isIdentical(in, reply);
                    }
                case 12: 
                    if (method.equals("_get_EJBHome")) {
                        return _get_EJBHome(in, reply);
                    }
                case 15: 
                    if (method.equals("_get_primaryKey")) {
                        return _get_primaryKey(in, reply);
                    }
                case 16: 
                    if (method.equals("hpCreateWcsOrder")) {
                        return hpCreateWcsOrder(in, reply);
                    }
                case 20: 
                    if (method.equals("hpAmountTobeRefunded")) {
                        return hpAmountTobeRefunded(in, reply);
                    }
                case 21: 
                    if (method.equals("hpGetRMANumberService")) {
                        return hpGetRMANumberService(in, reply);
                    }
                case 24: 
                    if (method.equals("hpSendReturnOrderDetails")) {
                        return hpSendReturnOrderDetails(in, reply);
                    }
                case 25: 
                    if (method.equals("hpCreateNarvarReturnOrder")) {
                        return hpCreateNarvarReturnOrder(in, reply);
                    } else if (method.equals("hpUpdateNarvarReturnOrder")) {
                        return hpUpdateNarvarReturnOrder(in, reply);
                    } else if (method.equals("hpCancelNarvarReturnOrder")) {
                        return hpCancelNarvarReturnOrder(in, reply);
                    }
                case 32: 
                    if (method.equals("hpSendValidOrdersForReturnClient")) {
                        return hpSendValidOrdersForReturnClient(in, reply);
                    }
            }
            throw new BAD_OPERATION();
        } catch (SystemException ex) {
            throw ex;
        } catch (Throwable ex) {
            throw new UnknownException(ex);
        }
    }
    
    private OutputStream _get_EJBHome(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        EJBHome result = target.getEJBHome();
        OutputStream out = reply.createReply();
        Util.writeRemoteObject(out,result);
        return out;
    }
    
    private OutputStream _get_primaryKey(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        Object result = target.getPrimaryKey();
        OutputStream out = reply.createReply();
        Util.writeAny(out,result);
        return out;
    }
    
    private OutputStream remove(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        try {
            target.remove();
        } catch (RemoveException ex) {
            String id = "IDL:javax/ejb/RemoveEx:1.0";
            org.omg.CORBA_2_3.portable.OutputStream out = 
                (org.omg.CORBA_2_3.portable.OutputStream) reply.createExceptionReply();
            out.write_string(id);
            out.write_value(ex,RemoveException.class);
            return out;
        }
        OutputStream out = reply.createReply();
        return out;
    }
    
    private OutputStream _get_handle(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        Handle result = target.getHandle();
        OutputStream out = reply.createReply();
        Util.writeAbstractObject(out,result);
        return out;
    }
    
    private OutputStream isIdentical(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        EJBObject arg0 = (EJBObject) in.read_Object(EJBObject.class);
        boolean result = target.isIdentical(arg0);
        OutputStream out = reply.createReply();
        out.write_boolean(result);
        return out;
    }
    
    private OutputStream hpGetRMANumberService(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        OrderXSDType arg0 = (OrderXSDType) in.read_value(OrderXSDType.class);
        XBeanWSEnv arg1 = (XBeanWSEnv) in.read_value(XBeanWSEnv.class);
        String arg2 = (String) in.read_value(String.class);
        RMAXSDType result = target.hpGetRMANumberService(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,RMAXSDType.class);
        return out;
    }
    
    private OutputStream hpAmountTobeRefunded(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        com.hp.sterling.jaxws.webservices.documentation.hpamounttoberefunded.hpamounttoberefunded.input.OrderXSDType arg0 = (com.hp.sterling.jaxws.webservices.documentation.hpamounttoberefunded.hpamounttoberefunded.input.OrderXSDType) in.read_value(com.hp.sterling.jaxws.webservices.documentation.hpamounttoberefunded.hpamounttoberefunded.input.OrderXSDType.class);
        XBeanWSEnv arg1 = (XBeanWSEnv) in.read_value(XBeanWSEnv.class);
        String arg2 = (String) in.read_value(String.class);
        com.hp.sterling.jaxws.webservices.documentation.hpamounttoberefunded.hpamounttoberefunded.output.OrderXSDType result = target.hpAmountTobeRefunded(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,com.hp.sterling.jaxws.webservices.documentation.hpamounttoberefunded.hpamounttoberefunded.output.OrderXSDType.class);
        return out;
    }
    
    private OutputStream hpSendReturnOrderDetails(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        com.hp.sterling.jaxws.webservices.documentation.sendreturnorderdetails.hpsendreturnorderdetails.input.OrderXSDType arg0 = (com.hp.sterling.jaxws.webservices.documentation.sendreturnorderdetails.hpsendreturnorderdetails.input.OrderXSDType) in.read_value(com.hp.sterling.jaxws.webservices.documentation.sendreturnorderdetails.hpsendreturnorderdetails.input.OrderXSDType.class);
        XBeanWSEnv arg1 = (XBeanWSEnv) in.read_value(XBeanWSEnv.class);
        String arg2 = (String) in.read_value(String.class);
        OrderListXSDType result = target.hpSendReturnOrderDetails(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,OrderListXSDType.class);
        return out;
    }
    
    private OutputStream hpSendValidOrdersForReturnClient(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        com.hp.sterling.jaxws.webservices.documentation.sendvalidordersforreturn.hpsendvalidordersforreturn.input.OrderXSDType arg0 = (com.hp.sterling.jaxws.webservices.documentation.sendvalidordersforreturn.hpsendvalidordersforreturn.input.OrderXSDType) in.read_value(com.hp.sterling.jaxws.webservices.documentation.sendvalidordersforreturn.hpsendvalidordersforreturn.input.OrderXSDType.class);
        XBeanWSEnv arg1 = (XBeanWSEnv) in.read_value(XBeanWSEnv.class);
        String arg2 = (String) in.read_value(String.class);
        com.hp.sterling.jaxws.webservices.documentation.sendvalidordersforreturn.hpsendvalidordersforreturn.output.OrderListXSDType result = target.hpSendValidOrdersForReturnClient(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,com.hp.sterling.jaxws.webservices.documentation.sendvalidordersforreturn.hpsendvalidordersforreturn.output.OrderListXSDType.class);
        return out;
    }
    
    private OutputStream hpCreateWcsOrder(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        com.hp.sterling.jaxws.webservices.documentation.createwcsorder.hpcreatewcsorder.input.OrderXSDType arg0 = (com.hp.sterling.jaxws.webservices.documentation.createwcsorder.hpcreatewcsorder.input.OrderXSDType) in.read_value(com.hp.sterling.jaxws.webservices.documentation.createwcsorder.hpcreatewcsorder.input.OrderXSDType.class);
        XBeanWSEnv arg1 = (XBeanWSEnv) in.read_value(XBeanWSEnv.class);
        String arg2 = (String) in.read_value(String.class);
        com.hp.sterling.jaxws.webservices.documentation.createwcsorder.hpcreatewcsorder.output.OrderXSDType result = target.hpCreateWcsOrder(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,com.hp.sterling.jaxws.webservices.documentation.createwcsorder.hpcreatewcsorder.output.OrderXSDType.class);
        return out;
    }
    
    private OutputStream hpCreateNarvarReturnOrder(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        com.hp.sterling.jaxws.webservices.documentation.createnarvarreturnorder.createnarvarreturnorder.input.OrderXSDType arg0 = (com.hp.sterling.jaxws.webservices.documentation.createnarvarreturnorder.createnarvarreturnorder.input.OrderXSDType) in.read_value(com.hp.sterling.jaxws.webservices.documentation.createnarvarreturnorder.createnarvarreturnorder.input.OrderXSDType.class);
        YFSEnvironmentXSDType arg1 = (YFSEnvironmentXSDType) in.read_value(YFSEnvironmentXSDType.class);
        String arg2 = (String) in.read_value(String.class);
        com.hp.sterling.jaxws.webservices.documentation.createnarvarreturnorder.createnarvarreturnorder.output.OrderXSDType result = target.hpCreateNarvarReturnOrder(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,com.hp.sterling.jaxws.webservices.documentation.createnarvarreturnorder.createnarvarreturnorder.output.OrderXSDType.class);
        return out;
    }
    
    private OutputStream hpUpdateNarvarReturnOrder(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        com.hp.sterling.jaxws.webservices.documentation.updatenarvarreturnorder.updatenarvarreturnorder.input.OrderXSDType arg0 = (com.hp.sterling.jaxws.webservices.documentation.updatenarvarreturnorder.updatenarvarreturnorder.input.OrderXSDType) in.read_value(com.hp.sterling.jaxws.webservices.documentation.updatenarvarreturnorder.updatenarvarreturnorder.input.OrderXSDType.class);
        YFSEnvironmentXSDType arg1 = (YFSEnvironmentXSDType) in.read_value(YFSEnvironmentXSDType.class);
        String arg2 = (String) in.read_value(String.class);
        ExtnFedExTransactionXSDType result = target.hpUpdateNarvarReturnOrder(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,ExtnFedExTransactionXSDType.class);
        return out;
    }
    
    private OutputStream hpCancelNarvarReturnOrder(org.omg.CORBA_2_3.portable.InputStream in , ResponseHandler reply) throws Throwable {
        com.hp.sterling.jaxws.webservices.documentation.cancelnarvarreturnorder.cancelnarvarreturnorder.input.OrderXSDType arg0 = (com.hp.sterling.jaxws.webservices.documentation.cancelnarvarreturnorder.cancelnarvarreturnorder.input.OrderXSDType) in.read_value(com.hp.sterling.jaxws.webservices.documentation.cancelnarvarreturnorder.cancelnarvarreturnorder.input.OrderXSDType.class);
        YFSEnvironmentXSDType arg1 = (YFSEnvironmentXSDType) in.read_value(YFSEnvironmentXSDType.class);
        String arg2 = (String) in.read_value(String.class);
        com.hp.sterling.jaxws.webservices.documentation.cancelnarvarreturnorder.cancelnarvarreturnorder.output.OrderXSDType result = target.hpCancelNarvarReturnOrder(arg0, arg1, arg2);
        org.omg.CORBA_2_3.portable.OutputStream out = 
            (org.omg.CORBA_2_3.portable.OutputStream) reply.createReply();
        out.write_value((Serializable)result,com.hp.sterling.jaxws.webservices.documentation.cancelnarvarreturnorder.cancelnarvarreturnorder.output.OrderXSDType.class);
        return out;
    }
}